#Этап сборки
FROM node:16-alpine AS builder
#Устанавливаем рабочую директорию
WORKDIR /app
#Копируем файлы с зависимостями
COPY package*.json ./
#Устанавливаем 
RUN npm i
#Копируем все содержимое корневой папки в /app
COPY . ./

#запускаем сборку / удаляем исходники в src / удаляем зависимости
RUN npm run build \
  && rm -rf ./src \
  && rm -rf node ./node_modules

#Этап развертывания фронтенд части приложения через nginx. nginx занимается проксированием портов и раздачей статических файлов
FROM nginx:1.23.1-alpine AS frontend
WORKDIR /app
#Копируем файлы из этапа builder
COPY --from=builder /app/build ./usr/share/nginx/html
COPY ./nginx/conf.d/default.conf ./etc/nginx/conf.d/default.conf
EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]