version: '3.2'
services:
  backend:
    container_name: backend
    image: vladislavser/backend-kupipodaridai:1.0.0
    env_file: .env.example
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - backend_network
    volumes:
      - type: bind
        source: ./backend/src
        target: /app/src
  frontend:
    container_name: frontend
    image: vladislavser/frontend-kupipodaridai:1.0.0
    ports:
      - '3001:3000'
    restart: unless-stopped
    networks:
      - frontend_network
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    env_file: .env.example
    volumes:
      - pg_data:/data/postgres
    networks:
      - backend_network
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - postgres
    networks:
      - backend_network
volumes:
  pg_data:
networks:
  backend_network:
  frontend_network:
